title: User Name's Homepage
page-top-title: 阮颢宁
top-section-bg-text: 微电子科学与工程
backgrounds:
  - static/assets/background/GDUT1.jpg
  - static/assets/background/GDUT2.jpg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; '
github-link:
  text: Github
  href: https://github.com/tomatoglue94
license-link:
  text: License
  href: https://github.com/tomatoglue94/tomatoglue94/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: User Name&ensp;|&ensp;阮颢宁
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
