title: User Name's Homepage
page-top-title: 阮颢宁
top-section-bg-text: 微电子科学与工程
backgrounds:
  - static/assets/background/GDUT1.jpg
  - static/assets/background/GDUT2.jpg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Haoning Ruan 2026-now. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/tomatoglue94
license-link:
  text: License
  href: https://github.com/tomatoglue94/tomatoglue94/blob/main/LICENSE
sections:
  - id: home
    nav: 首页
    title: Haoning Ruan&ensp;|&ensp;阮颢宁
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: 成果
    title: 成果
    icon: bi-file-text-fill
  - id: awards
    nav: 奖项
    title: 奖项
    icon: bi-award-fill
